Feature/cache queries and add combined indicators
toggle-corp/ifrc-gates-backend pull request #120
Opened 2022-09-29 05:04 UTC by bimal125

- Addresses xxxxxx (eg: #1)
- Depends on xxxxxx (eg: #1)

## Changes

* Added separate query for combined indicators
* Cached overview table data
* Cached overview map data
* Cached combined indicators

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)

2022-09-29 11:11 UTC, Rup-Narayan-Rajbanshi commented on apps/visualization/utils.py
> +                        'topic_description': topic['topic_description'],
I think It seems to raise error "topic is not defined",

2022-09-29 11:12 UTC, Rup-Narayan-Rajbanshi approved these changes

2022-10-17 10:14 UTC, thenav56 requested changes
Looks good. Few changes.

2022-10-17 10:14 UTC, thenav56 commented on apps/visualization/dataloaders.py
> +    _map = defaultdict(str)
Should be int right?

2022-10-17 10:14 UTC, thenav56 commented on apps/visualization/filters.py
>          print(topic)
```suggestion
```

2022-10-17 10:14 UTC, thenav56 commented on apps/visualization/utils.py
> +            return {}
```suggestion
        return {}
```

2022-10-19 05:01 UTC, merged